### ISSUE TITLE
pihole-exporter crashes unexpactedly

### ISSUE THREAD

**Issue by Videothek** [eko/pihole-exporter#125]
Since my last upgrade of the pihole-exporter i experience unperiodical crashes of the exporter.
Today I ran the exporter manually to catch any error if it occurs.

So this is the error after pihole-exporter running fine for about 8 hours:

```
ERRO[26500] An error has occured during login to PI-Hole: Post "http://pihole_ip:80/admin/index.php?login": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x39e740]

goroutine 25215 [running]:
net/http.(*Response).Cookies(...)
        /usr/local/go/src/net/http/response.go:126
github.com/eko/pihole-exporter/internal/pihole.(*Client).getPHPSessionID(0x263c390, 0x2642295, 0x627d0)
        /opt/pihole-exporter/internal/pihole/client.go:165 +0x414
github.com/eko/pihole-exporter/internal/pihole.(*Client).authenticateRequest(0x263c390, 0x2518680)
        /opt/pihole-exporter/internal/pihole/client.go:220 +0x1c
github.com/eko/pihole-exporter/internal/pihole.(*Client).getStatistics(0x263c390, 0x4694fe, 0x12, 0x273afc4)
        /opt/pihole-exporter/internal/pihole/client.go:190 +0x374
github.com/eko/pihole-exporter/internal/pihole.(*Client).CollectMetricsAsync(0x263c390, 0x4eea48, 0x25c01e0, 0x2518600)
        /opt/pihole-exporter/internal/pihole/client.go:82 +0x8c
created by github.com/eko/pihole-exporter/internal/server.NewServer.func1
        /opt/pihole-exporter/internal/server/server.go:38 +0xc0
```

**Steps for Reproduction**

1. Launch pihole with standard options
2. Let it run till it crashes

**Expected behavior**: should run permanantly without issues

**Actual behavior**: crashes after some time e.g 8 hours

**Platforms**: Ubuntu Server 20.04 on ARM

**Versions**: should be 0.3.0

I will try to upgrade the exporter to see if this helps.

**Comment by Videothek** [comment]
So after upgrading to a new go version and downloading pihole-exporter again the exporter is running for three days now.

I consider the problem fixed and will close this topic.
