### ISSUE TITLE
Docker container crashing

### ISSUE THREAD

**Issue by cacack** [eko/pihole-exporter#40]
The docker container crashes due to a timeout accessing dockerized pihole.  The pihole container works, and is accessible on 192.168.1.1:80, so not sure what the problem is for pihole_exporter.   Maybe host networking mode and the elevated privlages pihole needs for DHCP?

**Steps for Reproduction**

docker-compose.yaml:
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'super-secret'
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
      DNSSEC: "True"
      ServerIP: "192.168.1.1"
      INTERFACE: "eth0"
      DNSMASQ_LISTENING: "eth0"
    # Volumes store your data between container upgrades
    volumes:
       - '/srv/pihole/config/:/etc/pihole/'
       - '/srv/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

 pihole_exporter:
    container_name: pihole_exporter
    image: ekofr/pihole-exporter:latest
    ports:
      - "9617:9617"
    environment:
      PIHOLE_HOSTNAME: 192.168.1.1
      PIHOLE_PASSWORD: super-secret
      INTERVAL: 30s
```
2. Run it
```
docker-compose up -d
```
3. After a few seconds pihole_exporter crashes.

**Expected behavior**:

pihole_exporter is started

**Actual behavior**:

It crashes.  Following are in the docker logs:
```
2020/04/16 23:26:15 ------------------------------------
2020/04/16 23:26:15 -  PI-Hole exporter configuration  -
2020/04/16 23:26:15 ------------------------------------
2020/04/16 23:26:15 PIHoleHostname : 192.168.1.1
2020/04/16 23:26:15 Port : 9617
2020/04/16 23:26:15 Interval : 30s
2020/04/16 23:26:15 ------------------------------------
2020/04/16 23:26:15 New Prometheus metric registered: domains_blocked
2020/04/16 23:26:15 New Prometheus metric registered: dns_queries_today
2020/04/16 23:26:15 New Prometheus metric registered: ads_blocked_today
2020/04/16 23:26:15 New Prometheus metric registered: ads_percentag_today
2020/04/16 23:26:15 New Prometheus metric registered: unique_domains
2020/04/16 23:26:15 New Prometheus metric registered: queries_forwarded
2020/04/16 23:26:15 New Prometheus metric registered: queries_cached
2020/04/16 23:26:15 New Prometheus metric registered: clients_ever_seen
2020/04/16 23:26:15 New Prometheus metric registered: unique_clients
2020/04/16 23:26:15 New Prometheus metric registered: dns_queries_all_types
2020/04/16 23:26:15 New Prometheus metric registered: reply
2020/04/16 23:26:15 New Prometheus metric registered: top_queries
2020/04/16 23:26:15 New Prometheus metric registered: top_ads
2020/04/16 23:26:15 New Prometheus metric registered: top_sources
2020/04/16 23:26:15 New Prometheus metric registered: forward_destinations
2020/04/16 23:26:15 New Prometheus metric registered: querytypes
2020/04/16 23:26:15 New Prometheus metric registered: status
2020/04/16 23:26:15 Starting HTTP server
2020/04/16 23:27:15 An error has occured during login to PI-Hole: Post "http://192.168.1.1/admin/index.php?login": dial tcp 192.168.1.1:80: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7a7a52]

goroutine 34 [running]:
net/http.(*Response).Cookies(...)
	/usr/local/go/src/net/http/response.go:126
github.com/eko/pihole-exporter/internal/pihole.(*Client).getPHPSessionID(0xc00019a770, 0xc000038790, 0xc000038701)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:121 +0x512
github.com/eko/pihole-exporter/internal/pihole.(*Client).Scrape(0xc00019a770)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:50 +0x1dd
created by main.initPiholeClient
	/go/src/github.com/eko/pihole-exporter/main.go:37 +0x75
```

**Platforms**:

Running on Alpine Linux 3.11, docker 19.03.5

**Versions**:

latest

**Comment by eko** [comment]
Hello @cacack,

It seems that the PI Hole container cannot contact your PI-Hole host `192.168.1.1`. Could you please try to replace:
```
      PIHOLE_HOSTNAME: 192.168.1.1
```

with the container name / host, accessible inside containers:

```
      PIHOLE_HOSTNAME: pihole
```

Also, it's not normal that the app crashed with this kind of exception, I will have a look based on your stacktrace.

Thanks :)

**Comment by cacack** [comment]
Sorry it took a while to get back to this.  After some experimentation, it looks like it has something to do with the pihole docker running in host networking mode.  Changing the pihole_exporter to also use host networking avoided the connection timeout, and therefore the exception.

**Comment by cacack** [comment]
I'll also note that not using host networking and trying various values for the `PIHOLE_HOSTNAME` environment variable resulted in no change -- still an IO timeout followed by the exception being thrown.

With the host networking, I've set `PIHOLE_HOSTNAME` to 127.0.0.1.

**Comment by eko** [comment]
@cacack Great, so it's working now using the host networking? I don't think this issue is related to the pihole-exporter docker image but more on how to use it.

Thank you for your feedbacks anyway

**Comment by logopk** [comment]
Hi. I see the same issue.

```
2020/05/24 04:04:32 New tick of statistics: 250 ads blocked / 35172 total DNS queries
2020/05/24 04:05:44 An error has occured during login to PI-Hole: Post "http://pi-hole/admin/index.php?login": dial tcp: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x3461f0]

goroutine 38 [running]:
net/http.(*Response).Cookies(...)
	/usr/local/go/src/net/http/response.go:126
github.com/eko/pihole-exporter/internal/pihole.(*Client).getPHPSessionID(0x20161e0, 0x4, 0x204b9c0)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:120 +0x3f0
github.com/eko/pihole-exporter/internal/pihole.(*Client).authenticateRequest(0x20161e0, 0x20e2200)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:175 +0x1c
github.com/eko/pihole-exporter/internal/pihole.(*Client).getStatistics(0x20161e0, 0x20b6fd0)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:145 +0x330
github.com/eko/pihole-exporter/internal/pihole.(*Client).Scrape(0x20161e0)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:51 +0x80
created by main.initPiHoleClient
	/go/src/github.com/eko/pihole-exporter/main.go:37 +0x70

```
>   pihole-exporter:
>     image: ekofr/pihole-exporter:0.0.9
>     container_name: pihole-exporter
>     hostname: pihole-exporter
>     labels:
>       - "org.label-schema.group=monitoring"
>     restart: always
>     external_links:
>       - pi-hole
>     environment:
>       - TZ=Europe/Berlin
>       - PIHOLE_HOSTNAME=pi-hole
>       - PIHOLE_PASSWORD
>       - INTERVAL=60s
>       - PORT=8080
>     networks:
>       - pihole_default

Pihole is on it's own network.

And for what I noticed once, it was really low level, as I was unable to restart, remove or kill the container. Only kill on the containerd process worked. 

Any chance to debug it?

Peter

**Comment by Kampe** [comment]
I see the same issues with only one of my pihole instances, the other, configured completely the same, does not exhibit this behavior so I'm confused.

```
pihole-exporter    | 2020/07/26 23:40:08 New Prometheus metric registered: status
pihole-exporter    | 2020/07/26 23:40:08 Starting HTTP server
pihole-exporter    | 2020/07/26 23:40:38 An error has occured during login to PI-Hole: Post "http://127.0.0.1/admin/index.php?login": dial tcp 127.0.0.1:80: connect: connection refused
pihole-exporter    | panic: runtime error: invalid memory address or nil pointer dereference
pihole-exporter    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x3461f0]
pihole-exporter    |
pihole-exporter    | goroutine 50 [running]:
pihole-exporter    | net/http.(*Response).Cookies(...)
pihole-exporter    | 	/usr/local/go/src/net/http/response.go:126
pihole-exporter    | github.com/eko/pihole-exporter/internal/pihole.(*Client).getPHPSessionID(0xdac190, 0x4, 0xd030c0)
pihole-exporter    | 	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:120 +0x3f0
pihole-exporter    | github.com/eko/pihole-exporter/internal/pihole.(*Client).authenticateRequest(0xdac190, 0xcb6000)
pihole-exporter    | 	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:175 +0x1c
pihole-exporter    | github.com/eko/pihole-exporter/internal/pihole.(*Client).getStatistics(0xdac190, 0xdba7d0)
pihole-exporter    | 	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:145 +0x330
pihole-exporter    | github.com/eko/pihole-exporter/internal/pihole.(*Client).Scrape(0xdac190)
pihole-exporter    | 	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:51 +0x80
pihole-exporter    | created by main.initPiHoleClient
pihole-exporter    | 	/go/src/github.com/eko/pihole-exporter/main.go:37 +0x70
```

**Comment by Kampe** [comment]
Well, helps if pihole isn't crashlooping and can respond to requests.  Turns out the fix is just being more defensive about the login if pihole is potentially down maybe catch the case and return that in the logs

**Comment by eko** [comment]
Hi,

The answer is in the error message you filled:
```yaml
dial tcp 127.0.0.1:80: connect: connection refused
```

The exporter cannot connect to PI-Hole API on 127.0.0.1 (port 80). I think you have passed a wrong value.

Closing this issue for now but feel free to reopen if you still have an issue with the exporter.
