### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by daven1985** [eko/pihole-exporter#59]
Good Evening,

When I try and run it I get the following error... thoughts?

```
2020/08/12 11:29:12 Starting HTTP server
2020/08/12 11:29:22 An error has occured during retrieving PI-Hole statistics Get "http://127.0.0.1:80/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject": dial tcp 127.0.0.1:80: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7a9426]

goroutine 25 [running]:
github.com/eko/pihole-exporter/internal/pihole.(*Client).getStatistics(0xc0000d83f0, 0xc00003a790)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:163 +0x2f6
github.com/eko/pihole-exporter/internal/pihole.(*Client).Scrape(0xc0000d83f0)
	/go/src/github.com/eko/pihole-exporter/internal/pihole/client.go:61 +0x83
created by main.initPiHoleClient
	/go/src/github.com/eko/pihole-exporter/main.go:37 +0xc0

```

**Comment by eko** [comment]
Hi,

I think you have a wrong hostname/port for your PI-Hole installation, please take a look at the README file.

Closing this issue for now, feel free to reopen if you think you still have an issue.
